-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('HelloWorld_pb')


local HELLOWORLD = protobuf.Descriptor();
local HELLOWORLD_ID_FIELD = protobuf.FieldDescriptor();
local HELLOWORLD_STR_FIELD = protobuf.FieldDescriptor();
local HELLOWORLD_OPT_FIELD = protobuf.FieldDescriptor();

HELLOWORLD_ID_FIELD.name = "id"
HELLOWORLD_ID_FIELD.full_name = ".lm.HelloWorld.id"
HELLOWORLD_ID_FIELD.number = 1
HELLOWORLD_ID_FIELD.index = 0
HELLOWORLD_ID_FIELD.label = 2
HELLOWORLD_ID_FIELD.has_default_value = false
HELLOWORLD_ID_FIELD.default_value = 0
HELLOWORLD_ID_FIELD.type = 5
HELLOWORLD_ID_FIELD.cpp_type = 1

HELLOWORLD_STR_FIELD.name = "str"
HELLOWORLD_STR_FIELD.full_name = ".lm.HelloWorld.str"
HELLOWORLD_STR_FIELD.number = 2
HELLOWORLD_STR_FIELD.index = 1
HELLOWORLD_STR_FIELD.label = 2
HELLOWORLD_STR_FIELD.has_default_value = false
HELLOWORLD_STR_FIELD.default_value = ""
HELLOWORLD_STR_FIELD.type = 9
HELLOWORLD_STR_FIELD.cpp_type = 9

HELLOWORLD_OPT_FIELD.name = "opt"
HELLOWORLD_OPT_FIELD.full_name = ".lm.HelloWorld.opt"
HELLOWORLD_OPT_FIELD.number = 3
HELLOWORLD_OPT_FIELD.index = 2
HELLOWORLD_OPT_FIELD.label = 1
HELLOWORLD_OPT_FIELD.has_default_value = false
HELLOWORLD_OPT_FIELD.default_value = 0
HELLOWORLD_OPT_FIELD.type = 5
HELLOWORLD_OPT_FIELD.cpp_type = 1

HELLOWORLD.name = "HelloWorld"
HELLOWORLD.full_name = ".lm.HelloWorld"
HELLOWORLD.nested_types = {}
HELLOWORLD.enum_types = {}
HELLOWORLD.fields = {HELLOWORLD_ID_FIELD, HELLOWORLD_STR_FIELD, HELLOWORLD_OPT_FIELD}
HELLOWORLD.is_extendable = false
HELLOWORLD.extensions = {}

HelloWorld = protobuf.Message(HELLOWORLD)

